### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by PatriciaTendai** [ds4owd-001/md-03-assignments-PatriciaTendai#1]
@larnsce @mianzg @sskorik01

**Comment by PatriciaTendai** [comment]
I think I am lost in pushing the assignments. 

I check the boxes under Git and commit (from posit cloud)
A new tab pops up and I commit again, then everything disappears 
am I supposed to push a blank page?

thanks

**Comment by PatriciaTendai** [comment]
@larnsce @mianzg @sskorik01 
I think I am lost in pushing the assignments.
I check the boxes under Git and commit (from posit cloud)
A new tab pops up and I commit again, then everything disappears
am I supposed to push a blank page?

thanks

**Comment by sskorik01** [comment]
Hi, 

From what I can see you successfully pushed your part b) of module 3 assignment. Just to recap, you have to check the boxes of all the files you want to commit & push, then press on commit

![Image](https://github.com/ds4owd-001/md-03-assignments-PatriciaTendai/assets/148224762/933c674d-742d-4196-999f-77bdf2ab2605)

Then, you have a window that appears showing all your changes (in green), you have to enter a commit message on the top right and then press commit again

![Image](https://github.com/ds4owd-001/md-03-assignments-PatriciaTendai/assets/148224762/f62cf909-23bd-459c-b614-bb5ca1b0da1a)

You then have a window appearing, where it is written the number of changes you have done in the file. You can close this file. 

![Image](https://github.com/ds4owd-001/md-03-assignments-PatriciaTendai/assets/148224762/ce52f1e7-745f-4c65-976f-95109e5aa662)

The last step is to push your code. You can press on the push button, enter your PAT and then push. 

![Image](https://github.com/ds4owd-001/md-03-assignments-PatriciaTendai/assets/148224762/e172dc4e-0ca0-4815-aaa4-61d9d3cd45f3)

I hope this helps!

**Comment by PatriciaTendai** [comment]
> Hi,
> 
> From what I can see you successfully pushed your part b) of module 3 assignment. Just to recap, you have to check the boxes of all the files you want to commit & push, then press on commit
> 
> ![Image](https://user-images.githubusercontent.com/148224762/284353348-933c674d-742d-4196-999f-77bdf2ab2605.png)
> 
> Then, you have a window that appears showing all your changes (in green), you have to enter a commit message on the top right and then press commit again
> 
> ![Image](https://user-images.githubusercontent.com/148224762/284353349-f62cf909-23bd-459c-b614-bb5ca1b0da1a.png)
> 
> You then have a window appearing, where it is written the number of changes you have done in the file. You can close this file.
> 
> ![Image](https://user-images.githubusercontent.com/148224762/284353347-ce52f1e7-745f-4c65-976f-95109e5aa662.png)
> 
> The last step is to push your code. You can press on the push button, enter your PAT and then push.
> 
> ![Image](https://user-images.githubusercontent.com/148224762/284353346-e172dc4e-0ca0-4815-aaa4-61d9d3cd45f3.png)
> 
> I hope this helps!

Thanks, this helps.
